### ISSUE TITLE
Check user actions for current dialog stack.

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botframework-skills#345]
## Version
Calendar v2

## Describe the bug
- show tomorrow meeting, it will show a meeting list. eg. 15 meetings
- show today meeting, it will show today's meeting list. eg. only 1 meeting
- click one of meeting items for "tomorrow meeting list"
- it show error as below
![image](https://user-images.githubusercontent.com/43408889/98088793-dd467800-1ebc-11eb-8811-30c53aac1d8b.png)

* As the dialog stack changed, so today's meeting list only have 1, if user click the meeting item listed in old steps, it will companies error. Could we provide more user friendly error or check the user action in advance ? 

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by Quirinevwm** [comment]
Good point this one, we need to think about adding transcript potentially - let me explain my thinking

Scenario: user asks about what's on Wednesday, then asks about today again and get's a new overview, but then decides to scroll back in the chat to Wednesday's overview and clicks on a meeting to see the details. 

Apparently an error occurs, since we cannot go back in the chat and click on previous asked overviews? (double check @lauren-mills)
Can we recognize when a user has clicked on an older card that is inactive with new transcript:
**"I cannot retrieve that info again, can you ask me again"
"Unfortunate, those insights could be outdated, can you ask me again"**

**Comment by lauren-mills** [comment]
I actually started working on a solution to this yesterday that will allow you to click the old results as well. Should have it in today

**Comment by lauren-mills** [comment]
This is resolved
