### ISSUE TITLE
Context for meeting list card

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botframework-skills#348]
## Version
Calendar V2

## Describe the bug
Give a clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/43408889/98102480-a2e5d680-1ece-11eb-93a4-3b730b8c8d83.png)

Expect the condition for the card. eg. I say "show tomorrow", the card should not display "show tomorrow".

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by Quirinevwm** [comment]
Thanks for sharing in our call too, yes let's update the transcript for the button - since the routing is still the same  of showing the next day based on the current day shown in the card.

Logic for transcript edit: 
When shown for "Today" - button = **"Show tomorrow"**
When shown for "Tomorrow" & "Any other day/date call out (that is not today)" - button = **"Next day"**
