### ISSUE TITLE
Test/Bug: No suggestions due to timezones

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#352]
Discovered by booking time with L (Seattle) and D (London):
- When there is working hour overlap (London & Amsterdam) - I get suggestions : known bug that card is too large, Yue working on it #340 
- No overlap (Seattle & Amsterdam) - I get none - we skip the suggestion step - so can we add transcript here (I've added to the transcript file):
**"I can't suggest a time to meet since you have no overlap in working hours, what day did you have in mind?"
"You seem to have no overlap in working hours, what day did you have in mind?"**

![image](https://user-images.githubusercontent.com/43533472/98113890-9cdb0000-1ea4-11eb-9896-94e57434d0f6.png)

**Comment by lauren-mills** [comment]
Did you invite someone from microsoft.com when you tried this? This feature will only work with people whose accounts we have access to through the graph so that might be the issue.

**Comment by Quirinevwm** [comment]
> Did you invite someone from microsoft.com when you tried this? This feature will only work with people whose accounts we have access to through the graph so that might be the issue.

Just tied out by inviting you (no suggestion) & Em (also skipping that step):
Plus the language model is not picking up I've included a contact in my utterance
![image](https://user-images.githubusercontent.com/43533472/98352370-3bd73780-201e-11eb-8782-50cedc5fd0f1.png)

**Comment by xhr0804** [comment]
@Quirinevwm  The ms-graph can only return an empty suggestion reason like:
![image](https://user-images.githubusercontent.com/44257569/98781814-ec37a800-2431-11eb-91ff-898f3cc73aa3.png)
We can not exactly know whether it is because there is not overlap in the timezone or some other reasons.
But I guess mostly it is because of the timezone difference, because we won't add other limitations when use the api.
So could we change the transcript a little bit, like
"I can't suggest a time to meet, maybe it's because you have no overlap in working hours, what day did you have in mind?"
or something like that?

**Comment by Quirinevwm** [comment]
@xhr0804 as discussed, probable is that it's dye to time overlap. Please use the following transcript:
"I can't suggest a time to meet, probably because there is no overlap in working hours. What day did you want to meet?"
"I have no suggestions for you, probably there is no overlap in working hours. What day did you have in mind?"
