### ISSUE TITLE
Test/Bug: too much to show in card (search/find/overview) so updated transcript needed

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#360]
For find and overview of day in chat, if the events (contacts, suggestion times) are too many, let's use the following logic & transcript:
25 events logic is:
- 25 = 5 pages max
- default = 1 month

Transcript
≥ 5 - 25 events
**I’ve found [#] events for [Date] that match your request:
There's [#] events for [Date] that match your search:
[#] events match your search criteria for [Date]:
You have [#] events on [Date] that match your search:**
 
≥ 25 (only logic for showing 25 events)
**There are too many events to show. If you want to narrow it down, please provide me with a bit more context. For now, I'll share the first 25 events:
OK, I found many events, I'll just share the first 25. If you want to narrow it down, please ask me again and provide a bit more context.**

≥ 25 events (count total amount of events + show 25)
**I’ve found [#] events for [Date], these are too much to show in one go. The first [25] events are:
There's [#] events for [Date], that's too many events to show. I'm sharing the first [25]:
[#] events match your search criteria for [Date]. I'm sharing the first [25]:
You have [#] events on [Date], I will show the first [25]:**

+ When testing big lists, the transcript showed some duplication & odd start:
![image](https://user-images.githubusercontent.com/43533472/98248356-193d1400-1f75-11eb-8838-d9944ab18d3d.png)

**Comment by lauren-mills** [comment]
@Quirinevwm - can you test this one again? I think we've added limits to everything now but want to make sure before closing this

**Comment by Quirinevwm** [comment]
> @Quirinevwm - can you test this one again? I think we've added limits to everything now but want to make sure before closing this

It works but have a few notes:
- for "Find/Search" can we put in the "I'm searching your calendar, this might take a sec..." + the alterations, since it does take quite long. Is it possible to only use that transcript for "find" - I would not like it to appear for "overview of day".
- Paging works, I like th e"updated in the top left corner"
![image](https://user-images.githubusercontent.com/43533472/99148785-04a1ff80-268a-11eb-93a0-d0025f1f4799.png)
![image](https://user-images.githubusercontent.com/43533472/99148827-3915bb80-268a-11eb-842c-1374e05fe21f.png)

**Comment by lauren-mills** [comment]
A few notes here. For the "Find meetings with [name]" intent right now we are using the GetEventTitle intent which will tell you the name of a particular event but it expects you to select it from a list. I think we should reconsider the design a bit once the dogfood launches, because I don't think that's quite right for what we're trying to do. 

This is what we support right now:

1. If a user asks about a specific day or date range, we show the **Schedule Card**
1. If they ask for "who/when/where/what" we search based on the entities, then expect them to select one of the options then we show the **EventDetailCard** with a message based on what they asked for

I think instead, when they ask for "what", like "what do I have with Elaine" or "what do I have tomorrow afternoon" we should just show the list and not expect them to select something. I think for "who/when/where" it makes sense for them to choose only one.

Also, the personName entity doesn't recognize "Em". We can discuss switching to using a custom entity in a later sprint, or pairing it with the personName to try to pick up more options.

**Comment by lauren-mills** [comment]
I'm also removing those buttons from the FindEvent for now. It is technically an active prompt that's expecting a selection, so I think the buttons are a little confusing in that context. Once we make the change above, I think it will make more sense to add them back

**Comment by lauren-mills** [comment]
I made a small change to the transcript that should hopefully reduce confusion for now, but we can change this to not be a prompt in the next sprint:

![image](https://user-images.githubusercontent.com/27976702/99178420-c1ff1800-26c7-11eb-9d59-96b75d12afba.png)

**Comment by lauren-mills** [comment]
- Updated the "I found [#]..." lg responses
- Added the "This may take a while" responses
- Removed the buttons (didn't work and out of context)
- Added "please select an option" to lead the user in the right direction for now
- Added more training data for "find meeting with [name]" etc

**Comment by Quirinevwm** [comment]
Taking the buttons out also makes the list look cleaner, for overview of day and accept/decline it makes sense to keep them in, for all the rest yes take them out!

I think the rationale makes sense what you are proposing as the right direction, so that will mean:
-  "what" questions return a list with no action for the user to select. 
- with ""who/when/where" questions we return a list (same as "what"), then a user can decide if they want to follow up and skill return per default "You can select an option:"
