### ISSUE TITLE
Test/Bug: update (also triggered with move) does not work

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#391]
Q to update LG with "move" as a part for update:
Now move triggers - create
Should preferably: understand that the meeting needs to **only be update based on time**
![image](https://user-images.githubusercontent.com/43533472/98851511-a93bfb80-2456-11eb-9476-0c90f466aa45.png)

It did figure out update in the end & breaks:
![image](https://user-images.githubusercontent.com/43533472/98851604-c8d32400-2456-11eb-86f3-7cf419e8a2aa.png)

**Comment by KayMKM** [comment]
@lauren-mills To support "move my lunch meeting tomorrow to 12:30pm" we need to distinguish old time and new time. So I try to add two roles for datetimev2 entity. But we can only get time from whole sentence now. If we want to get the exactly text of every datetimev2 entity, we need to add a predictionOptions in generated files. Current Composer client will override the generated files every bot restart. And the latest Composer has fixed this issue. But I am not sure should we upgrade the client now? Because the latest Composer doesn't public release so may have potential issues. Or do you have any suggestion to fix this issue?

**Comment by lauren-mills** [comment]
@KayMKM - Hm, maybe we can do a combination. You could add the roles for datetimeV2 entity, then run the text for each recognized entity through the resolve datetime dialog (we have to do this to get the right timezone information). That should give you both role to indicate the "current time" and "new time" and the correct resolutions. Will that work?

I agree I don't think we should update our composer clients until we get the dogfood out.

**Comment by KayMKM** [comment]
@lauren-mills Yes, that is what I mean. When bot calls luis predict endpoint with a option called "includeInstanceData" as true, then luis will return a result with instance data. This feature has been supported in lastest Composer.

**Comment by lauren-mills** [comment]
Let's put this on hold for now. Quirine hasn't marked it as blocking the dogfood testing so we can keep it in the backlog until we are at a place to update to the latest composer client.

**Comment by lauren-mills** [comment]
As long as the utterance triggers the update flow as expected that is okay for now.

**Comment by Quirinevwm** [comment]
> As long as the utterance triggers the update flow as expected that is okay for now.

yes I will work on the LG today, so including "move" as a trigger for "update" is OK for now.
